[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1_000_000
gas_reports = ['ChainLinkResolver']
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
mainnet = "${RPC_ETHEREUM}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "${ETHERSCAN_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
